<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INLT-J1GVBS3" failures="2" tests="10" name="PetStore_User_Test" time="20.532" errors="0" timestamp="2025-08-27T16:17:23 IST">
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="3.658"/>
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="1.3"/>
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="1.377"/>
  <testcase classname="api.test.DataDrivenTests" name="deleteUsersbyName" time="1.433">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTests.deleteUsersbyName(DataDrivenTests.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- deleteUsersbyName -->
  <testcase classname="api.test.DataDrivenTests" name="deleteUsersbyName" time="1.502"/>
  <testcase classname="api.test.DataDrivenTests" name="deleteUsersbyName" time="1.43"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="1.384"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.433">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testGetUserByName(UserTests.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="2.863"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.447"/>
</testsuite> <!-- PetStore_User_Test -->
